[default]
description = "Default permissions for the plugin"
permissions = ["allow-get-fcm-token", "allow-request-push-permission","allow-get-apns-token","allow-registerListener","allow-unregister-listener"]
