[default]
description = "Default permissions for the plugin"
permissions = ["allow-get-fcm-token", "allow-get-apns-token","allow-registerListener","allow-unregister-listener","allow-checkPermissions","allow-requestPermissions"]
